server:
  port: 8081

guns:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
  file-upload-path: /hyxt/img       #文件上传目录(不配置的话为java.io.tmpdir目录)
#  file-upload-path: d:/tmp       #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

spring:
  profiles:
    active: @spring.active@
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  resources:
#    static-locations: classpath:/static/**,classpath:/.well-known/**
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.stylefeng.guns.modular.system.model

log:
  path: /hyxt/app/logfile

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://47.92.75.142:3306/changsha_guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: Xxkj@123
    db-name: changsha_guns_test #用来搜集数据库的所有表
    filters: wall,mergeStat

#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    url: jdbc:mysql://47.92.75.132:3306/changsha_guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    dataSourceNames:
      - dataSourceGuns
      - dataSourceBiz

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.92.75.132:3306/guns4_0?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    db-name: guns_5 #用来搜集数据库的所有表
    filters: wall,mergeStat

---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://47.92.75.132:3306/guns4_0?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root

    filters: wall,mergeStat

---

spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://192.168.0.105:3306/guns4_0?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      filters: wall,mergeStat

     # nohup java  -Xms400m -Xmx400m -Xmn200m  -jar  mina.jar > catalina.out  2>&1 &
     # nohup java  -Xms400m -Xmx400m -Xmn200m  -jar  xx.jar > catalina.out  2>&1 &
     # nohup java  -Xms400m -Xmx400m -Xmn200m  -jar  xx.jar   2>&1 &     netstat -tunlp|grep 8086

